name: GitHub Actions Demo
run-name: Build Deploy
on: [push]
jobs:
  build-push-registry:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      registry_token: ${{ secrets.REGISTRY_TOKEN }}
      registry_path: registry.digitalocean.com/smart-attendance
      do_user: ${{ secrets.DIGITAL_OCEAN_PASSWORD }}
      do_pass: ${{ secrets.DIGITAL_OCEAN_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Registry Login
        run: docker login -u ${{ env.registry_token }} -p ${{ env.registry_token }} registry.digitalocean.com

      - name: Build
        run: docker build -t smart-attendance-bff:latest .

      - name: Tag and Push
        run: | 
          docker tag smart-attendance-bff:latest ${{env.registry_path}}/smart-attendance-bff:latest && 
          docker push ${{env.registry_path}}/smart-attendance-bff:latest

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."