name: GitHub Actions Demo
run-name: Build Deploy - Staging
on: [push]
jobs:
  build-push-registry:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      registry_pass: ${{ secrets.REGISTRY_PASS }}
      registry_user: ${{ secrets.REGISTRY_USER }}
      registry_path: registry.digitalocean.com/smart-attendance
      do_user: ${{ secrets.DIGITAL_OCEAN_PASSWORD }}
      do_pass: ${{ secrets.DIGITAL_OCEAN_USER }}
      server_ip: 157.230.212.240
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.registry_user }}
          password: ${{ env.registry_pass }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: victorffernandes/smart-attendance-bff:latest

      - name: Setup SSH
        run: echo "${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}" > private_key 

      - name: Deploy
        run: | 
          scp -i private_key docker-compose-staging.yml root@157.230.212.240:/root &&
          ssh -i private_key root@${{ env.server_ip }} -f 'docker compose -f docker-compose-staging.yml down' &&
          ssh -i private_key root@${{ env.server_ip }} -f 'docker compose -f docker-compose-staging.yml up -d'

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."